---
title: "Casino Task Model & Parameter Recovery"
date: "11/4/2021"
output: 
  html_document:
    df_print: paged
    theme: flatly
    toc: yes
    toc_depth: 4
    toc_float: yes
---
<style type="text/css">
h1.title {
font-size: 38px;
}
h1 { /* Header 1 */
font-size: 28px;
}
h2 { /* Header 2 */
font-size: 22px;
}
h3 { /* Header 3 */
font-size: 18px;
}

</style>
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = T)
knitr::opts_chunk$set(fig.path = "figures/")
knitr::opts_chunk$set(fig.width=5, fig.height = 4.5, dpi = 600)
```

```{r load libraries and functions}
# Load needed libraries
library(tidyverse)
library(glue)
library(ggtext)
library(magrittr)

#standard error function
se <- function(x){
  sd(x, na.rm = T)/sqrt(length(x))
}
```

```{r define file names}
#define directory name
modeling_dir <- 'RL_modeling/output'

#bic values for each dataset & model
bic_recov_name <- glue("{modeling_dir}/bic_recovery.csv")

#simulated and recovered parameter values from four LR model
sim_params_name <- glue("{modeling_dir}/fourLR_sim_params.csv")
fit_params_name <- glue("{modeling_dir}/fourLR_fit_params.csv")

#proportion of optimal choices from model simulations
oneLR_choices_name <- glue("{modeling_dir}/one_LR_mean_opt_choices_sim.csv") 
twoLR_choices_name <- glue("{modeling_dir}/two_LR_mean_opt_choices_sim.csv") 
fourLR_choices_name <- glue("{modeling_dir}/four_LR_mean_opt_choices_sim.csv") 
```

```{r define plot aesthetics }
#define colors to use for plots
color1 = "#FFDD3C"
color2 = "#378bf1"
color3 = "grey"

#define plotting theme
casino.theme <- theme(panel.background = element_rect(fill='transparent'),
                    axis.line = element_line(color='black'),
                    panel.grid.minor = element_line(color='transparent'),
                    axis.title.x = element_text(size=16, vjust=-.25),
                    axis.title.y = element_text(size=16, vjust=1),
                    axis.text.x = element_text(size=12, colour="black"),
                    axis.text.y = element_text(size=12, colour="black"),
                    legend.text=element_text(size=12),
                    legend.title = element_text(size = 14),
                    plot.title = element_text(size=16, face = "bold", hjust = .5), 
                    strip.text.x = element_text(size=12), 
                    strip.text.y = element_text(size=12, face="bold"), 
                    strip.background = element_rect(colour= "black", fill = "transparent"))
```

# Parameter recovery
```{r import param data}

#read in simulated and fit parameters
sim_params <- read_csv(sim_params_name) %>%
  rename_with(~paste0(., "_sim")) %>%
  mutate(sub = 1:n())
  
fit_params <- read_csv(fit_params_name) %>%
  rename_with(~paste0(., "_fit")) %>%
  mutate(sub = 1:n())

#combine
params <- full_join(sim_params, fit_params, by = c("sub"))
```

```{r beta plot}
beta_plot <- ggplot(params, aes(x = beta_sim, y = beta_fit)) +
  geom_point(color = color2, alpha = .4, size = 1) +
  geom_smooth(method = "lm", color = "black") +
  xlab("Simulated Parameter") +
  ylab("Recovered Parameter") +
  annotate("text", 
           x = 27, y = 0, 
           label=(paste0("italic(r)==", round(cor(params$beta_sim, params$beta_fit),2))),
           parse = T) +
   labs(title="\u03B2") +
  casino.theme
beta_plot
```

```{r alpha_pos_risk_good plot}
alpha_pos_risk_good_plot <- ggplot(params, aes(x = alpha_pos_risk_good_sim, y = alpha_pos_risk_good_fit)) +
  geom_point(color = color2, alpha = .4, size = 1) +
  geom_smooth(method = "lm", color = "black", se = F)  +
  xlab("Simulated Parameter") +
  ylab("Recovered Parameter") +
  annotate("text", 
           x = .9, y = 0, 
           label=(paste0("italic(r)==", round(cor(params$alpha_pos_risk_good_sim, params$alpha_pos_risk_good_fit),2))),
           parse = T) +
   labs(title="\u03B1 pos, risk good") +
  casino.theme
alpha_pos_risk_good_plot
```

```{r alpha_neg_risk_good plot}
alpha_neg_risk_good_plot <- ggplot(params, aes(x = alpha_neg_risk_good_sim, y = alpha_neg_risk_good_fit)) +
  geom_point(color = color2, alpha = .4, size = 1) +
  geom_smooth(method = "lm", color = "black", se = F)  +
  xlab("Simulated Parameter") +
  ylab("Recovered Parameter") +
  annotate("text", 
           x = .9, y = 0, 
           label=(paste0("italic(r)==", round(cor(params$alpha_neg_risk_good_sim, params$alpha_neg_risk_good_fit),2))),
           parse = T) +
   labs(title="\u03B1 neg, risk good") +
  casino.theme
alpha_neg_risk_good_plot
```

```{r alpha_pos_risk_bad plot}
alpha_pos_risk_bad_plot <- ggplot(params, aes(x = alpha_pos_risk_bad_sim, y = alpha_pos_risk_bad_fit)) +
  geom_point(color = color2, alpha = .4, size = 1) +
  geom_smooth(method = "lm", color = "black", se = F) +
  xlab("Simulated Parameter") +
  ylab("Recovered Parameter") +
  annotate("text", 
           x = .9, y = 0, 
           label=(paste0("italic(r)==", round(cor(params$alpha_pos_risk_bad_sim, params$alpha_pos_risk_bad_fit),2))),
           parse = T) +
   labs(title="\u03B1 pos, risk bad") +
  casino.theme
alpha_pos_risk_bad_plot
```

```{r alpha_neg_risk_bad plot}
alpha_neg_risk_bad_plot <- ggplot(params, aes(x = alpha_neg_risk_bad_sim, y = alpha_neg_risk_bad_fit)) +
  geom_point(color = color2, alpha = .4, size = 1) +
  geom_smooth(method = "lm", color = "black", se = F) +
  xlab("Simulated Parameter") +
  ylab("Recovered Parameter") +
  annotate("text", 
           x = .9, y = 0, 
           label=(paste0("italic(r)==", round(cor(params$alpha_neg_risk_bad_sim, params$alpha_neg_risk_bad_fit),2))),
           parse = T) +
   labs(title="\u03B1 neg, risk bad") +
  casino.theme
alpha_neg_risk_bad_plot
```

# Model recovery
```{r read in model recovery results}
bic_recov <- read_csv(bic_recov_name, skip = 1, col_names = c('sim', 'fit'))
```

```{r recovery plot, fig.height = 4.5, fig.width = 5}
BIC_props <- bic_recov %>%
  mutate(sim = factor(sim, levels = c("one_LR", "two_LR", "four_LR")),
         fit = factor(fit, levels = c(3, 2, 1))) %>%
  group_by(sim, fit, .drop = F) %>%
  summarise(n = n(), .drop = F) %>%
  mutate(freq = n/sum(n), .drop = F)
                                
BIC_props_plot <- ggplot(BIC_props, aes(sim, fit, fill = freq)) +
  geom_tile(color = "black", aes(size = factor(freq))) +
  scale_size_manual(values = c(.25, .25, .25, .25, .25, .25, .75, .75, .75), guide = "none") +
  geom_text(aes(label = round(freq, 2))) +
  scale_fill_gradient(low = "white", high = color2, "Proportion Best Fit", 
                      guide = "none") +
  scale_x_discrete(labels = c("1 LR", "2 LR", "4 LR"), name = "Simulated Model") +
  scale_y_discrete(labels = c("4 LR", "2 LR", "1 LR"), name = "Recovered Model") +
  casino.theme
 BIC_props_plot 
```

# Simulated vs. real data
```{r import simulated data}
sim_oneLR <- read_csv(oneLR_choices_name) %>%
  mutate(trial = 1:n(), 
         model = "1LR") %>%
  pivot_longer(cols = 1:6,  names_to = "group", values_to = "prop_opt") %>%
  separate(col = "group", sep = "_", into = c("age_group", "block_order")) 

sim_twoLR <- read_csv(twoLR_choices_name) %>%
  mutate(trial = 1:n(),
         model = "2LR") %>%
  pivot_longer(cols = 1:6,  names_to = "group", values_to = "prop_opt") %>%
  separate(col = "group", sep = "_", into = c("age_group", "block_order"))

sim_fourLR <- read_csv(fourLR_choices_name) %>%
  mutate(trial = 1:n(),
         model = "4LR") %>%
  pivot_longer(cols = 1:6,  names_to = "group", values_to = "prop_opt") %>%
  separate(col = "group", sep = "_", into = c("age_group", "block_order"))

sim_data <- rbind(sim_oneLR, sim_twoLR, sim_fourLR) %>%
  mutate(block_order = case_when(block_order == 1 ~ "Risk Good First",
                                 block_order == 2 ~ "Risk Bad First"),
         block_type = case_when(as.numeric(trial) < 101 & block_order == "Risk Good First" ~ "Risk Good",
                                as.numeric(trial) > 100 & block_order == "Risk Good First" ~ "Risk Bad",
                                as.numeric(trial) < 101 & block_order == "Risk Bad First" ~ "Risk Bad",
                                as.numeric(trial) > 100 & block_order == "Risk Bad First" ~ "Risk Good"),
         trial_num = case_when(as.numeric(trial) < 101 ~ as.numeric(trial),
                               as.numeric(trial) > 100 ~ (as.numeric(trial) - 100)),
         age_group = factor(age_group, levels = c("Children", "Adolescents", "Adults")))
```


```{r read in data}
#define data directory
data_dir = "data/task_data/"

#get list of files
data_files <- list.files(path = data_dir, pattern = "*.csv")

#get list of subject ages
sub_ages <- read_csv("data/other_data_files/sub_ages.csv")

#initialize data frame
data <- data.frame()

# Read in data
for (i in c(1:length(data_files))){
  sub_data <- read_csv(glue("{data_dir}{data_files[i]}"), show_col_types = F) 
  
  #compute the number of browser interactions
  num_interactions = length(str_split(tail(sub_data,1)$interactions, pattern = "\r\n")[[1]]) - 2
  sub_data$num_interactions <- num_interactions
  
  #compute number of quiz questions answered correctly
  num_quiz_attempts = nrow(sub_data %>% 
                             filter(trial_type == "casino-comp_q"))
  sub_data$quiz_attempts <- num_quiz_attempts
  
  #add numeric id to use in matlab later
  sub_data$matlab_id <- i
  
  #combine subject data into larger data frame
  data <- rbind(data, sub_data)
}

# read in list of subjects to include
included_subs <- read_csv("data/other_data_files/sub_ages_inc.csv")

#join with data
filtered_data <- inner_join(data, included_subs, by = c("sub_id")) 

#re-order age groups
filtered_data %<>% mutate(age_group = 
                            factor(age_group, levels = c("Children", "Adolescents", "Adults")))
```

```{r filtered data processing}
learning_data <- filtered_data %>%
      select(c(trial_index,
           sub_id,
           matlab_id,
           age,
           age_group,
           risk_good_first,
           block1_A,
           block1_B, 
           block1_C,
           block1_D,
           block2_A, 
           block2_B,
           block2_C,
           block2_D,
           stimulus,
           task_part,
           card_choice,
           rt,
           choice_position,
           points_earned,
           block,
           num_interactions,
           quiz_attempts)) %>%
    filter(task_part == "real_trial") 

#recode points earned, RT, card choices, risk type, and block type
learning_data %<>% mutate(points_earned = as.numeric(points_earned),
                         rt = as.numeric(rt),
                         card_letter = case_when(card_choice == block1_A ~ "A",
                                         card_choice == block2_A ~ "A",
                                         card_choice == block1_B ~ "B",
                                         card_choice == block2_B ~ "B",
                                         card_choice == block1_C ~ "C",
                                         card_choice == block2_C ~ "C",
                                         card_choice == block1_D ~ "D",
                                         card_choice == block2_D ~ "D"),
                         card_type = case_when(card_letter == "A" ~ "risky",
                                       card_letter == "B" ~ "risky",
                                       card_letter == "C" ~ "safe",
                                       card_letter == "D" ~ "safe"), 
                         block_number = as.factor(block),
                         block_type = case_when(risk_good_first == "TRUE" & block == 1 ~ "Risk Good",
                                        risk_good_first == "TRUE" & block == 2 ~ "Risk Bad",
                                        risk_good_first == "FALSE" & block == 1 ~ "Risk Bad",
                                        risk_good_first == "FALSE" & block == 2 ~ "Risk Good"))

#determine optimal choices
optimal_choices <- learning_data %>%
  mutate(optimal_choice = case_when(block_type == "Risk Good" & card_type == "risky" ~ 1,
                                    block_type == "Risk Good" & card_type == "safe" ~ 0,
                                    block_type == "Risk Bad" & card_type == "risky" ~ 0,
                                    block_type == "Risk Bad" & card_type == "safe" ~ 1),
         block_order = case_when(risk_good_first == FALSE ~ "Risk Bad First",
                                 risk_good_first == TRUE ~ "Risk Good First"))

# determine each participant's proportion of optimal choices within each trial group
sub_optimal_choices <- optimal_choices %>%
  group_by(sub_id, block_type, block_order) %>%
  mutate(trial = rank(trial_index)) %>%
  ungroup() %>%
  group_by(trial, block_type, age_group, block_order) %>%
  summarize(prop_optimal = mean(optimal_choice, na.rm = T)) %>%
  mutate(data_type = "participants") %>%
  ungroup() %>%
  select(model = data_type, age_group, block_order, prop_opt = prop_optimal, block_type, trial_num = trial)
```

```{r combine real data and simulated 4LR}
fourLR_choices <- sim_data %>%
  select(-trial)

combined_data <- rbind(fourLR_choices, sub_optimal_choices)
```

```{r plot simulated and real data, fig.width = 6}
#compute means per trial group
optimal_choice_means <- combined_data %>%
  mutate(trial_group = ceiling(trial_num/20)) %>%
  group_by(trial_group, block_type, age_group, model, block_order) %>%
  summarize(mean_opt_choice = mean(prop_opt)) %>%
  mutate(model = factor(model))
  
#plot optimal choices over time
optimal_choice_plot_1 <- ggplot(optimal_choice_means %>% filter(block_order == "Risk Good First"), 
                              aes(x = trial_group,
                                  y = mean_opt_choice, 
                                  color = model,
                                  linetype = model)) +
  facet_grid(cols = vars(age_group), rows = vars(block_type)) +
  geom_line(aes(group = model), size = .75) +
  geom_point() +
  scale_color_manual(values = c("darkorange", "darkred", "darkblue", "black"), name = "") +
  scale_linetype_manual(values = c(2, 3, 5, 1), name = "") +
  geom_hline(yintercept = .5, color = "grey", linetype = "dashed") +
  xlab("Trial Group (20 trials)") +
  ylab("Proportion of Optimal Choices") +
  casino.theme +
  theme(legend.position = "top") +
  ggtitle("Risk Good First") +
        theme(panel.border = element_rect(fill = NA, size = .5),
    panel.background = element_blank(),
    axis.line = element_blank()) 
optimal_choice_plot_1

optimal_choice_plot_2 <- ggplot(optimal_choice_means %>% filter(block_order == "Risk Bad First"), 
                              aes(x = trial_group,
                                  y = mean_opt_choice, 
                                  color = model,
                                  linetype = model)) +
  facet_grid(cols = vars(age_group), rows = vars(block_type)) +
  geom_line(aes(group = model), size = .75) +
  geom_point() +
  scale_color_manual(values = c("darkorange", "darkred", "darkblue", "black"), name = "") +
  scale_linetype_manual(values = c(2, 3, 5, 1), name = "") +
  geom_hline(yintercept = .5, color = "grey", linetype = "dashed") +
  xlab("Trial Group (20 trials)") +
  ylab("Proportion of Optimal Choices") +
  casino.theme +
  theme(legend.position = "top") +
  ggtitle("Risk Bad First") +
        theme(panel.border = element_rect(fill = NA, size = .5),
    panel.background = element_blank(),
    axis.line = element_blank()) 
optimal_choice_plot_2
```

```{r plot simulated and real data collapsed across block order, fig.width = 6}
#compute means per trial group
optimal_choice_means <- combined_data %>%
  mutate(trial_group = ceiling(trial_num/10)) %>%
  group_by(trial_group, block_type, age_group, model) %>%
  summarize(mean_opt_choice = mean(prop_opt),
            se_opt_choice = se(prop_opt)) %>%
  mutate(model = factor(model)) %>%
  filter(model %in% c("participants", "4LR"))
  
#plot optimal choices over time
optimal_choice_plot <- ggplot(optimal_choice_means, 
                              aes(x = trial_group,
                                  y = mean_opt_choice, 
                                  color = block_type,
                                  linetype = model,
                                  shape = model)) +
  facet_grid(cols = vars(age_group)) +
  geom_line(size = .75) +
  coord_cartesian(ylim = c(.3, .8)) +
  geom_point(size = 2) +
  geom_errorbar(data = optimal_choice_means %>% filter(model == "participants"), aes(ymin = mean_opt_choice - se_opt_choice, ymax = mean_opt_choice + se_opt_choice), width = .1, linetype = 1) +
  scale_color_manual(values = c(color1, color2), name = "") +
  scale_linetype_manual(values = c(1, 2), name = "") +
  scale_shape_manual(values = c(17, 20), name = "") +
  geom_hline(yintercept = .5, color = "grey", linetype = "dashed") +
  xlab("Trial Group (10 trials)") +
  scale_x_continuous(breaks = c(2, 4, 6, 8, 10)) +
  ylab("Proportion of Optimal Choices") +
  casino.theme +
  theme(legend.position = "top") +
        theme(panel.border = element_rect(fill = NA, size = .5),
    panel.background = element_blank(),
    axis.line = element_blank()) 
optimal_choice_plot
```


```{r plot mean and simulated data 2, fig.width = 8}
optimal_choice_means <- combined_data %>%
  mutate(trial_group = ceiling(trial_num/20)) %>%
  group_by(block_type, age_group, model, block_order) %>%
  summarize(mean_opt_choice = mean(prop_opt)) %>%
  mutate(model = factor(model))

opt_choice_plot_simple <- ggplot(optimal_choice_means, aes(x = block_type, color = model, y = mean_opt_choice, shape = model)) +
  facet_grid(cols = vars(age_group), rows = vars(block_order)) +
  coord_cartesian(ylim = c(.4, .8)) + 
  geom_point(size = 3) +
  geom_line(aes(group = model)) +
  ylab("Proportion of Optimal Choices") +
  xlab("Block Type") +
  scale_color_manual(values = c(color1, color2, color3, 'black'), name = "Model") +
  scale_shape_manual(values = c(20, 20, 20, 18), name = "Model") +
  casino.theme +
      theme(panel.border = element_rect(fill = NA, size = .5),
    panel.background = element_blank(),
    axis.line = element_blank()) 
opt_choice_plot_simple
```